# Generated by Django 2.1.15 on 2021-01-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210108_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedplants',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
